### PR TITLE
Fix renamer, lcov check was not accessing the proper object

### PR DESCRIPTION
**Pull request by elwayman02**
#67 contained a typo that prevents the renamer from actually working.  This PR fixes that issue to help enable #63

### CODE REVIEW

**Comment by jschilli** [comment]
@elwayman02 note failing tests

**Comment by elwayman02** [comment]
Ah, the test was written for the bad syntax as well.  Fixed.

**Comment by jschilli** [comment]
@elwayman02 thanks

**Comment by jrjohnson** [comment]
Nice!  I also followed this bad code up with a matching config file in my app.  Its amazing how wrong one guy can be huh?

**Pull request merged**
