### PR TITLE
Resolves #46 - removes bodyparser.urlencoded

### LINKED ISSUE #46: Puts and Posts failing when using "ember server --proxy"
I upgraded to 0.5.0 and now all the puts and posts are cancelled when going through a proxy similar to this [post](http://stackoverflow.com/questions/23856465/ember-cli-proxy-works-for-get-but-fails-on-put-and-post) from some time ago. Looking at the changes from version 4 to version 5, there is a middleware function in 5 index.js that includes the line 
```
app.use(bodyparser.urlencoded({ extended: true });
```
 If I comment out this line, my proxy starts to work again, however the lcovOptions outfile appears to no longer be produced, which is the reason we upgraded to 5.  Could you look into getting ember-blanket-cli to play nice with the proxy please.

### PR DESCRIPTION
**Pull request by jschilli**

### CODE REVIEW

**Comment by JohnQuaresma** [comment]
I'd like to pull this into my ember-cli app via npm.  Can you guys tag this version?  npm won't respect the sha-based git url.

Thanks!

**Comment by sglanzer** [comment]
Yep - I've got one more fix I'd like to merge before we tag.  Should be available soon.

**Comment by JohnQuaresma** [comment]
Cool.  Looking forward to it!

**Comment by sglanzer** [comment]
@JohnQuaresma Published in 0.5.1, sorry for the delay

**Comment by JohnQuaresma** [comment]
Great!  No problem :-)

**Pull request merged**
